use_frameworks!

platform :ios, '8.0'

target 'BMAlertController_Example' do
  pod 'BMAlertController', :path => '../'

  target 'BMAlertController_Tests' do
    inherit! :search_paths

    
  end
end
